//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HobbyKlub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int ToolId { get; set; }
        public int PartNo { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual Tool Tool { get; set; }
    }
}
