//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HobbyKlub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int MemberId { get; set; }
        public int ToolId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Status { get; set; }
        public int LocID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Tool Tool { get; set; }
    }
}
