//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HobbyKlub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public Tool()
        {
            this.Location = new HashSet<Location>();
            this.Part = new HashSet<Part>();
        }
    
        public int ToolId { get; set; }
        public string Name { get; set; }
        public byte[] Picture { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public int K_number { get; set; }
        public int Art { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Value { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Location> Location { get; set; }
        public virtual ICollection<Part> Part { get; set; }
    }
}
