//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace HobbyklubConverter
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Hobbyklub2Entities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Hobbyklub2Entities1 object using the connection string found in the 'Hobbyklub2Entities1' section of the application configuration file.
        /// </summary>
        public Hobbyklub2Entities1() : base("name=Hobbyklub2Entities1", "Hobbyklub2Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Hobbyklub2Entities1 object.
        /// </summary>
        public Hobbyklub2Entities1(string connectionString) : base(connectionString, "Hobbyklub2Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Hobbyklub2Entities1 object.
        /// </summary>
        public Hobbyklub2Entities1(EntityConnection connection) : base(connection, "Hobbyklub2Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LOGIN_OUT> LOGIN_OUT
        {
            get
            {
                if ((_LOGIN_OUT == null))
                {
                    _LOGIN_OUT = base.CreateObjectSet<LOGIN_OUT>("LOGIN_OUT");
                }
                return _LOGIN_OUT;
            }
        }
        private ObjectSet<LOGIN_OUT> _LOGIN_OUT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RESERVATION> RESERVATION
        {
            get
            {
                if ((_RESERVATION == null))
                {
                    _RESERVATION = base.CreateObjectSet<RESERVATION>("RESERVATION");
                }
                return _RESERVATION;
            }
        }
        private ObjectSet<RESERVATION> _RESERVATION;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UDLAAN> UDLAAN
        {
            get
            {
                if ((_UDLAAN == null))
                {
                    _UDLAAN = base.CreateObjectSet<UDLAAN>("UDLAAN");
                }
                return _UDLAAN;
            }
        }
        private ObjectSet<UDLAAN> _UDLAAN;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VAERKTOJ> VAERKTOJ
        {
            get
            {
                if ((_VAERKTOJ == null))
                {
                    _VAERKTOJ = base.CreateObjectSet<VAERKTOJ>("VAERKTOJ");
                }
                return _VAERKTOJ;
            }
        }
        private ObjectSet<VAERKTOJ> _VAERKTOJ;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LOGIN_OUT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLOGIN_OUT(LOGIN_OUT lOGIN_OUT)
        {
            base.AddObject("LOGIN_OUT", lOGIN_OUT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RESERVATION EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRESERVATION(RESERVATION rESERVATION)
        {
            base.AddObject("RESERVATION", rESERVATION);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UDLAAN EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUDLAAN(UDLAAN uDLAAN)
        {
            base.AddObject("UDLAAN", uDLAAN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VAERKTOJ EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVAERKTOJ(VAERKTOJ vAERKTOJ)
        {
            base.AddObject("VAERKTOJ", vAERKTOJ);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hobbyklub2Model", Name="LOGIN_OUT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LOGIN_OUT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LOGIN_OUT object.
        /// </summary>
        /// <param name="oPERATOR">Initial value of the OPERATOR property.</param>
        public static LOGIN_OUT CreateLOGIN_OUT(global::System.String oPERATOR)
        {
            LOGIN_OUT lOGIN_OUT = new LOGIN_OUT();
            lOGIN_OUT.OPERATOR = oPERATOR;
            return lOGIN_OUT;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OPERATOR
        {
            get
            {
                return _OPERATOR;
            }
            set
            {
                if (_OPERATOR != value)
                {
                    OnOPERATORChanging(value);
                    ReportPropertyChanging("OPERATOR");
                    _OPERATOR = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("OPERATOR");
                    OnOPERATORChanged();
                }
            }
        }
        private global::System.String _OPERATOR;
        partial void OnOPERATORChanging(global::System.String value);
        partial void OnOPERATORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LOGIN_DATO_TID
        {
            get
            {
                return _LOGIN_DATO_TID;
            }
            set
            {
                OnLOGIN_DATO_TIDChanging(value);
                ReportPropertyChanging("LOGIN_DATO_TID");
                _LOGIN_DATO_TID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOGIN_DATO_TID");
                OnLOGIN_DATO_TIDChanged();
            }
        }
        private Nullable<global::System.DateTime> _LOGIN_DATO_TID;
        partial void OnLOGIN_DATO_TIDChanging(Nullable<global::System.DateTime> value);
        partial void OnLOGIN_DATO_TIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LOGOUT_DATO_TID
        {
            get
            {
                return _LOGOUT_DATO_TID;
            }
            set
            {
                OnLOGOUT_DATO_TIDChanging(value);
                ReportPropertyChanging("LOGOUT_DATO_TID");
                _LOGOUT_DATO_TID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOGOUT_DATO_TID");
                OnLOGOUT_DATO_TIDChanged();
            }
        }
        private Nullable<global::System.DateTime> _LOGOUT_DATO_TID;
        partial void OnLOGOUT_DATO_TIDChanging(Nullable<global::System.DateTime> value);
        partial void OnLOGOUT_DATO_TIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hobbyklub2Model", Name="RESERVATION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RESERVATION : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RESERVATION object.
        /// </summary>
        /// <param name="k_NUMMER">Initial value of the K_NUMMER property.</param>
        public static RESERVATION CreateRESERVATION(global::System.Int32 k_NUMMER)
        {
            RESERVATION rESERVATION = new RESERVATION();
            rESERVATION.K_NUMMER = k_NUMMER;
            return rESERVATION;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LOENNUMMER
        {
            get
            {
                return _LOENNUMMER;
            }
            set
            {
                OnLOENNUMMERChanging(value);
                ReportPropertyChanging("LOENNUMMER");
                _LOENNUMMER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOENNUMMER");
                OnLOENNUMMERChanged();
            }
        }
        private Nullable<global::System.Int32> _LOENNUMMER;
        partial void OnLOENNUMMERChanging(Nullable<global::System.Int32> value);
        partial void OnLOENNUMMERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 K_NUMMER
        {
            get
            {
                return _K_NUMMER;
            }
            set
            {
                if (_K_NUMMER != value)
                {
                    OnK_NUMMERChanging(value);
                    ReportPropertyChanging("K_NUMMER");
                    _K_NUMMER = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("K_NUMMER");
                    OnK_NUMMERChanged();
                }
            }
        }
        private global::System.Int32 _K_NUMMER;
        partial void OnK_NUMMERChanging(global::System.Int32 value);
        partial void OnK_NUMMERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> STARTDATO
        {
            get
            {
                return _STARTDATO;
            }
            set
            {
                OnSTARTDATOChanging(value);
                ReportPropertyChanging("STARTDATO");
                _STARTDATO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STARTDATO");
                OnSTARTDATOChanged();
            }
        }
        private Nullable<global::System.DateTime> _STARTDATO;
        partial void OnSTARTDATOChanging(Nullable<global::System.DateTime> value);
        partial void OnSTARTDATOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SLUTDATO
        {
            get
            {
                return _SLUTDATO;
            }
            set
            {
                OnSLUTDATOChanging(value);
                ReportPropertyChanging("SLUTDATO");
                _SLUTDATO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SLUTDATO");
                OnSLUTDATOChanged();
            }
        }
        private Nullable<global::System.DateTime> _SLUTDATO;
        partial void OnSLUTDATOChanging(Nullable<global::System.DateTime> value);
        partial void OnSLUTDATOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OPERATOR
        {
            get
            {
                return _OPERATOR;
            }
            set
            {
                OnOPERATORChanging(value);
                ReportPropertyChanging("OPERATOR");
                _OPERATOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OPERATOR");
                OnOPERATORChanged();
            }
        }
        private global::System.String _OPERATOR;
        partial void OnOPERATORChanging(global::System.String value);
        partial void OnOPERATORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OPERATION_DATO
        {
            get
            {
                return _OPERATION_DATO;
            }
            set
            {
                OnOPERATION_DATOChanging(value);
                ReportPropertyChanging("OPERATION_DATO");
                _OPERATION_DATO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OPERATION_DATO");
                OnOPERATION_DATOChanged();
            }
        }
        private Nullable<global::System.DateTime> _OPERATION_DATO;
        partial void OnOPERATION_DATOChanging(Nullable<global::System.DateTime> value);
        partial void OnOPERATION_DATOChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hobbyklub2Model", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                if (_principal_id != value)
                {
                    Onprincipal_idChanging(value);
                    ReportPropertyChanging("principal_id");
                    _principal_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("principal_id");
                    Onprincipal_idChanged();
                }
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hobbyklub2Model", Name="UDLAAN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UDLAAN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UDLAAN object.
        /// </summary>
        /// <param name="k_NUMMER">Initial value of the K_NUMMER property.</param>
        public static UDLAAN CreateUDLAAN(global::System.Int32 k_NUMMER)
        {
            UDLAAN uDLAAN = new UDLAAN();
            uDLAAN.K_NUMMER = k_NUMMER;
            return uDLAAN;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LOENNUMMER
        {
            get
            {
                return _LOENNUMMER;
            }
            set
            {
                OnLOENNUMMERChanging(value);
                ReportPropertyChanging("LOENNUMMER");
                _LOENNUMMER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOENNUMMER");
                OnLOENNUMMERChanged();
            }
        }
        private Nullable<global::System.Int32> _LOENNUMMER;
        partial void OnLOENNUMMERChanging(Nullable<global::System.Int32> value);
        partial void OnLOENNUMMERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 K_NUMMER
        {
            get
            {
                return _K_NUMMER;
            }
            set
            {
                if (_K_NUMMER != value)
                {
                    OnK_NUMMERChanging(value);
                    ReportPropertyChanging("K_NUMMER");
                    _K_NUMMER = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("K_NUMMER");
                    OnK_NUMMERChanged();
                }
            }
        }
        private global::System.Int32 _K_NUMMER;
        partial void OnK_NUMMERChanging(global::System.Int32 value);
        partial void OnK_NUMMERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> STARTDATO
        {
            get
            {
                return _STARTDATO;
            }
            set
            {
                OnSTARTDATOChanging(value);
                ReportPropertyChanging("STARTDATO");
                _STARTDATO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STARTDATO");
                OnSTARTDATOChanged();
            }
        }
        private Nullable<global::System.DateTime> _STARTDATO;
        partial void OnSTARTDATOChanging(Nullable<global::System.DateTime> value);
        partial void OnSTARTDATOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SLUTDATO
        {
            get
            {
                return _SLUTDATO;
            }
            set
            {
                OnSLUTDATOChanging(value);
                ReportPropertyChanging("SLUTDATO");
                _SLUTDATO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SLUTDATO");
                OnSLUTDATOChanged();
            }
        }
        private Nullable<global::System.DateTime> _SLUTDATO;
        partial void OnSLUTDATOChanging(Nullable<global::System.DateTime> value);
        partial void OnSLUTDATOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OPERATOR
        {
            get
            {
                return _OPERATOR;
            }
            set
            {
                OnOPERATORChanging(value);
                ReportPropertyChanging("OPERATOR");
                _OPERATOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OPERATOR");
                OnOPERATORChanged();
            }
        }
        private global::System.String _OPERATOR;
        partial void OnOPERATORChanging(global::System.String value);
        partial void OnOPERATORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OPERATION_DATO
        {
            get
            {
                return _OPERATION_DATO;
            }
            set
            {
                OnOPERATION_DATOChanging(value);
                ReportPropertyChanging("OPERATION_DATO");
                _OPERATION_DATO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OPERATION_DATO");
                OnOPERATION_DATOChanged();
            }
        }
        private Nullable<global::System.DateTime> _OPERATION_DATO;
        partial void OnOPERATION_DATOChanging(Nullable<global::System.DateTime> value);
        partial void OnOPERATION_DATOChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Hobbyklub2Model", Name="VAERKTOJ")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VAERKTOJ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VAERKTOJ object.
        /// </summary>
        /// <param name="k_NUMMER">Initial value of the K_NUMMER property.</param>
        /// <param name="upsize_ts">Initial value of the upsize_ts property.</param>
        public static VAERKTOJ CreateVAERKTOJ(global::System.String k_NUMMER, global::System.Byte[] upsize_ts)
        {
            VAERKTOJ vAERKTOJ = new VAERKTOJ();
            vAERKTOJ.K_NUMMER = k_NUMMER;
            vAERKTOJ.upsize_ts = upsize_ts;
            return vAERKTOJ;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BESKRIV
        {
            get
            {
                return _BESKRIV;
            }
            set
            {
                OnBESKRIVChanging(value);
                ReportPropertyChanging("BESKRIV");
                _BESKRIV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BESKRIV");
                OnBESKRIVChanged();
            }
        }
        private global::System.String _BESKRIV;
        partial void OnBESKRIVChanging(global::System.String value);
        partial void OnBESKRIVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String K_NUMMER
        {
            get
            {
                return _K_NUMMER;
            }
            set
            {
                if (_K_NUMMER != value)
                {
                    OnK_NUMMERChanging(value);
                    ReportPropertyChanging("K_NUMMER");
                    _K_NUMMER = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("K_NUMMER");
                    OnK_NUMMERChanged();
                }
            }
        }
        private global::System.String _K_NUMMER;
        partial void OnK_NUMMERChanging(global::System.String value);
        partial void OnK_NUMMERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ANTAL_DELE
        {
            get
            {
                return _ANTAL_DELE;
            }
            set
            {
                OnANTAL_DELEChanging(value);
                ReportPropertyChanging("ANTAL_DELE");
                _ANTAL_DELE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ANTAL_DELE");
                OnANTAL_DELEChanged();
            }
        }
        private global::System.String _ANTAL_DELE;
        partial void OnANTAL_DELEChanging(global::System.String value);
        partial void OnANTAL_DELEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEL1
        {
            get
            {
                return _DEL1;
            }
            set
            {
                OnDEL1Changing(value);
                ReportPropertyChanging("DEL1");
                _DEL1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEL1");
                OnDEL1Changed();
            }
        }
        private global::System.String _DEL1;
        partial void OnDEL1Changing(global::System.String value);
        partial void OnDEL1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEL2
        {
            get
            {
                return _DEL2;
            }
            set
            {
                OnDEL2Changing(value);
                ReportPropertyChanging("DEL2");
                _DEL2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEL2");
                OnDEL2Changed();
            }
        }
        private global::System.String _DEL2;
        partial void OnDEL2Changing(global::System.String value);
        partial void OnDEL2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEL3
        {
            get
            {
                return _DEL3;
            }
            set
            {
                OnDEL3Changing(value);
                ReportPropertyChanging("DEL3");
                _DEL3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEL3");
                OnDEL3Changed();
            }
        }
        private global::System.String _DEL3;
        partial void OnDEL3Changing(global::System.String value);
        partial void OnDEL3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEL4
        {
            get
            {
                return _DEL4;
            }
            set
            {
                OnDEL4Changing(value);
                ReportPropertyChanging("DEL4");
                _DEL4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEL4");
                OnDEL4Changed();
            }
        }
        private global::System.String _DEL4;
        partial void OnDEL4Changing(global::System.String value);
        partial void OnDEL4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEL5
        {
            get
            {
                return _DEL5;
            }
            set
            {
                OnDEL5Changing(value);
                ReportPropertyChanging("DEL5");
                _DEL5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEL5");
                OnDEL5Changed();
            }
        }
        private global::System.String _DEL5;
        partial void OnDEL5Changing(global::System.String value);
        partial void OnDEL5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEL6
        {
            get
            {
                return _DEL6;
            }
            set
            {
                OnDEL6Changing(value);
                ReportPropertyChanging("DEL6");
                _DEL6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEL6");
                OnDEL6Changed();
            }
        }
        private global::System.String _DEL6;
        partial void OnDEL6Changing(global::System.String value);
        partial void OnDEL6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEL7
        {
            get
            {
                return _DEL7;
            }
            set
            {
                OnDEL7Changing(value);
                ReportPropertyChanging("DEL7");
                _DEL7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEL7");
                OnDEL7Changed();
            }
        }
        private global::System.String _DEL7;
        partial void OnDEL7Changing(global::System.String value);
        partial void OnDEL7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PRIS
        {
            get
            {
                return _PRIS;
            }
            set
            {
                OnPRISChanging(value);
                ReportPropertyChanging("PRIS");
                _PRIS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRIS");
                OnPRISChanged();
            }
        }
        private Nullable<global::System.Double> _PRIS;
        partial void OnPRISChanging(Nullable<global::System.Double> value);
        partial void OnPRISChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FEJLDATO
        {
            get
            {
                return _FEJLDATO;
            }
            set
            {
                OnFEJLDATOChanging(value);
                ReportPropertyChanging("FEJLDATO");
                _FEJLDATO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FEJLDATO");
                OnFEJLDATOChanged();
            }
        }
        private global::System.String _FEJLDATO;
        partial void OnFEJLDATOChanging(global::System.String value);
        partial void OnFEJLDATOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FEJLBESKRIVELSE
        {
            get
            {
                return _FEJLBESKRIVELSE;
            }
            set
            {
                OnFEJLBESKRIVELSEChanging(value);
                ReportPropertyChanging("FEJLBESKRIVELSE");
                _FEJLBESKRIVELSE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FEJLBESKRIVELSE");
                OnFEJLBESKRIVELSEChanged();
            }
        }
        private global::System.String _FEJLBESKRIVELSE;
        partial void OnFEJLBESKRIVELSEChanging(global::System.String value);
        partial void OnFEJLBESKRIVELSEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OKDATO
        {
            get
            {
                return _OKDATO;
            }
            set
            {
                OnOKDATOChanging(value);
                ReportPropertyChanging("OKDATO");
                _OKDATO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OKDATO");
                OnOKDATOChanged();
            }
        }
        private Nullable<global::System.DateTime> _OKDATO;
        partial void OnOKDATOChanging(Nullable<global::System.DateTime> value);
        partial void OnOKDATOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> REPPRIS
        {
            get
            {
                return _REPPRIS;
            }
            set
            {
                OnREPPRISChanging(value);
                ReportPropertyChanging("REPPRIS");
                _REPPRIS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("REPPRIS");
                OnREPPRISChanged();
            }
        }
        private Nullable<global::System.Int32> _REPPRIS;
        partial void OnREPPRISChanging(Nullable<global::System.Int32> value);
        partial void OnREPPRISChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DOK
        {
            get
            {
                return _DOK;
            }
            set
            {
                OnDOKChanging(value);
                ReportPropertyChanging("DOK");
                _DOK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DOK");
                OnDOKChanged();
            }
        }
        private global::System.String _DOK;
        partial void OnDOKChanging(global::System.String value);
        partial void OnDOKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BRUGERDOK
        {
            get
            {
                return _BRUGERDOK;
            }
            set
            {
                OnBRUGERDOKChanging(value);
                ReportPropertyChanging("BRUGERDOK");
                _BRUGERDOK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BRUGERDOK");
                OnBRUGERDOKChanged();
            }
        }
        private global::System.String _BRUGERDOK;
        partial void OnBRUGERDOKChanging(global::System.String value);
        partial void OnBRUGERDOKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] upsize_ts
        {
            get
            {
                return StructuralObject.GetValidValue(_upsize_ts);
            }
            set
            {
                if (!StructuralObject.BinaryEquals(_upsize_ts, value))
                {
                    Onupsize_tsChanging(value);
                    ReportPropertyChanging("upsize_ts");
                    _upsize_ts = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("upsize_ts");
                    Onupsize_tsChanged();
                }
            }
        }
        private global::System.Byte[] _upsize_ts;
        partial void Onupsize_tsChanging(global::System.Byte[] value);
        partial void Onupsize_tsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BILLEDE
        {
            get
            {
                return _BILLEDE;
            }
            set
            {
                OnBILLEDEChanging(value);
                ReportPropertyChanging("BILLEDE");
                _BILLEDE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BILLEDE");
                OnBILLEDEChanged();
            }
        }
        private global::System.String _BILLEDE;
        partial void OnBILLEDEChanging(global::System.String value);
        partial void OnBILLEDEChanged();

        #endregion

    
    }

    #endregion

    
}
